### ISSUE TITLE
Example link is broken

### ISSUE THREAD

**Issue by O4epegb** [ddmills/geotic#14]
Link to this  example `A larger example with pixi, rollup, and babel, can be found here.` is broken 

https://github.com/ddmills/geotic-example

**Comment by ddmills** [comment]
ah the link was private! this is fixed now.

I highly recommend checking out some of the work by @jdrew1303

* roguelike tutorial using geotic [jsrlt](https://github.com/luetkemj/jsrlt)
* complete roguelike game using geotic  [snail6](https://github.com/luetkemj/snail6)

i should add these to the readme

**Comment by jdrew1303** [comment]
Hey 🙋🏻‍♂️

I just seen this popping up in my notifications. I said I'd chime in. First off thanks again for goetic 👍Its really gained a lot of traction in the past few months which is really cool to see 😎

Ive actually kept the source closed at the moment. That might change but honestly its more of a group of experiments than a game. Its grand for ideas but I wouldn't be copying it as current best practise 😅🙈Anyway I thought I'd post the details I shared with you about my approach and maybe it might be of use to others:

> - Using [tone.js](https://tonejs.github.io/) to generate sounds and music. Positional audio is then handled using [songbird-audio](https://www.npmjs.com/package/songbird-audio) for higher order ambisonic rendering of the soundscape. (this is more or less ready to go)
> - I read a little bit about the development of No Man's Sky and their use of the [supershapes and superformula](supershapes and superformula). I managed to find a version for [generating three.js meshes](http://supershape.ahoi.in/). I'd like to use this to handle the generation of most of the models in the game. (An added bonus is that I don't have to save the mesh only the inputs for the formula and then I can generate them at runtime). (in the middle of adapting and optimising)
> - Im also using cannon.js for the physics system. I don't think I'll be using it for too much other than collision detection, gravity for jumping and maybe a few other bits and pieces. It will depend on how the rest goes. (working and [can generate cannon geometry from a three mesh](https://github.com/donmccurdy/three-to-cannon))
> - For the main game logic I was looking at probably using GURPS-like ruleset as the generic part. There is a bunch of different versions from a one page light version up to a full series of books. There's quite a bit of scope in there for a definition of 'completeness'. I need to figure out how to handle story arcs and the game master role though. I've been looking at something like [Ink](https://www.inklestudios.com/ink/). It's pretty powerful, with a good editor and has a javascript port of the runtime https://github.com/y-lohse/inkjs. The ability to branch the story arc and trigger events is more or less all a GM does. 
> - The last big technical item that I'm working on is the camera. Usually the three.js camera is a bit dumb and kind of clunky. Im planning on using [Yuka](https://mugen87.github.io/yuka) to add a nice AI to the camera for smart following, collision avoidance, etc. I want to see if I can treat it like it was another player that follows the main character. Similar to a documentary cinematographer. With this in mind I'm also doing a bit of work on creating 'lenses' for the camera to mimic some of the fields of view that you would get from 35mm and anamorphic lenses (I like photography so I figured why not). One interesting change though from a traditional camera is that I want to treat 'lens changes' as if they were like 'zooms'. There is no cut from one lens to anther but a transition. For this I'm using [animejs](https://animejs.com/) to handle the animation of the transitions from one fov/lens to another. 
> 
> Geotic is the glue that currently holds all this together. 

Since I wrote that some other little bits of info would be:
- To use Weak Maps for quite a bit of the systems. For example in the audio system you might have a sound component that holds the name of the sound to be played or a script that uses tonejs. You would use the component as the key for the map and the created audio node as the value. This way it's easy to serialise the entities. This also works for three objects and cannon objects, etc. 
- Don't forget that you can store function strings in a database and create scripted objects with the `Function` constructor. I wasted a lot of time finding alternatives and in the end went back to this (you can use `vm` on node or in electron).
- [Debug](https://github.com/visionmedia/debug) and [Controlkit](https://github.com/automat/controlkit.js) make debugging your game a lot easier.
- If you have perf issues run [cannonjs in a webworker](https://github.com/schteppe/cannon.js/blob/master/examples/worker.html) and [threejs in an offscreencanvas](https://threejsfundamentals.org/threejs/lessons/threejs-offscreencanvas.html).
- You can use [band.js](https://github.com/meenie/band.js) to generate audio which is more instrument based and plays nicely with song-bird and tone.js. You can also use anime.js for tweening of values.

Anyway hopefully these will be of help to people developing their own games. 
regards,
James 🙋🏻‍♂️

**Comment by jdrew1303** [comment]
Oh!!!! I forgot the core the my latest work. Webtorrent. You can use Webtorrent to handle asset loading. Honestly it might be a micro-optimisation but why not. It's cool and you'll learn a bunch. Plus a legit use for torrents. 😎
