### ISSUE TITLE
before lifecycle methods?

### ISSUE THREAD

**Issue by luetkemj** [ddmills/geotic#15]
Any chance for a beforeOnDetached lifecycle event?

I am using my Position component's `onAttached` method to add the id to an entities at location cache. I tried to use the `onDetached` method for removing it from that cache but by the time the method fires the Position component is already gone so I can't find the entity in my cache to remove it.

Would be great to expand on the lifecycle methods to allow for this.

**Comment by O4epegb** [comment]
@luetkemj I am following your tutorial and it is actually possible to do right now.

```
  onDetached() {
    const locId = `${this.x},${this.y}`;
    entitiesCache.delete(locId, this.entity.id);
  }
```

So `this` is actually component itself and it still has entity field with his entity it was attached. Although entity does not have `Position` already, but it does not needed.

**Comment by luetkemj** [comment]
This would still be useful for onDestroy() as you lose reference to the entity id when it is destroyed. Maybe this is related to #26 ?

**Comment by ddmills** [comment]
looking through the code I believe the components' entity should [still be present when `onDetached` is invoked](
https://github.com/ddmills/geotic/blob/master/src/Component.js#L83-L84)

If not, that sounds like a valid feature!

A related feature to this problem is a something recently implemented for queries, which allows you to react to [when an entity matches/unmatches the query](https://github.com/ddmills/geotic#queries). However, in that scenario the component is definitely already removed from the entity. I believe that could be switched though

**Comment by luetkemj** [comment]
> looking through the code I believe the components' entity should still be present when onDetached is invoked

☝️ this definitely works.

I'll give the query hook a try - sounds like it should work. It's would be nice to keep all the logic the reacts to adding and removing components in one place (the component definition) but maybe I can just move all of that to the queries and simplify the components... six of one, half dozen of the other. 🤷‍♀️

**Comment by ddmills** [comment]
@luetkemj I don't believe the query will have access to the component that was removed/added, but it has access to the `entity` that was changed

**Comment by ddmills** [comment]
closing, as this is solved with just referencing `this.entity` within `onDetached`
