### ISSUE TITLE
<Entity> and <EntityArray> seem to be gone

### ISSUE THREAD

**Issue by dcazrael** [ddmills/geotic#39]
In the docs, it says that these two elements exist.
When checking the commit history these two seem to have been removed recently.

Was this on purpose?
If so, is there an alternative?

Due to this, regular arrays have to be used instead of EntityArrays.
Not a big issue in itself, but then prototype functions are missing as well, which makes for an interesting bug hunt =)

Please let me know =)

**Comment by ddmills** [comment]
@dcazrael it has been removed in v4 due to extremely poor performance. I would really like to add it again in the future but I need a better way instead of using a Proxy for all properties. This is one of the reasons v4 is a major version bump

In this commit, i upgraded a very large project to geotic v4. The idea here was to store IDs (a reference to the entity) instead of the Entity itself. There is a helper file that provides some handy functions for implementing the getters/setters. It would be nice if this was a full feature of geotic again.

https://github.com/ddmills/sleepy/commit/24070a5de1155e757cb555c46c050fa5772cc764?branch=24070a5de1155e757cb555c46c050fa5772cc764&diff=split#diff-1cca721212e0b0b9f89fc299005f4b6d06affa4dc3a002e5c5f17b9a231b60ffR4-R16


The references to `<Entity>` and `<EntityArray>` need to be removed from the readme

**Comment by dcazrael** [comment]
Thank you. I have modeled the EntityArrays like in your example and it works nicely.

**Comment by ddmills** [comment]
#42
